{
    "name": "Sales: Goods & Transport Orders",
    "summary": "Adds 'Goods Orders' and 'Transport Orders' to Sales with context-driven behavior and billing automation.",
    "version": "18.0.1.0.0",
    "category": "Sales",
    "author": "rahways",
    "license": "LGPL-3",
    "depends": ["sale_management", "stock", "product", "sale_stock", "sale_margin", "account", "delivery", "partner_cost_centre", "product_harmonized_system"],
    "data": [
        "security/ir.model.access.csv",
        "data/order_sequence_data.xml",
        "views/bulk_invoice_wizard_views.xml",
        "views/container_report_views.xml",
        "views/inventory_reporting_views.xml",
        "views/res_config_settings_views.xml",
        "views/delivery_carrier_views.xml",
        "views/sale_order_views.xml",
        "views/menu.xml",
        "views/product_views.xml",
        "views/product_category_views.xml",
        "data/product_data.xml",
        "views/material_template_views.xml",
        "views/material_picking_wizard_views.xml",
        "views/stock_location_views.xml",
        "views/stock_picking_views.xml",
        "views/transport_product_line_views.xml",
        "views/stock_warehouse_views.xml",
        "views/sale_transport_leg_views.xml",
        "views/stock_package_type_views.xml",
        "report/transport_invoice_report.xml",
        "report/transport_invoice_templates.xml",
        "report/goods_invoice_report.xml",
        "report/goods_invoice_templates.xml",
    ],
    "installable": True,
    "application": False,
}
