from . import sale_order
from . import product_category
from . import product_template
from . import product_product
from . import account_move
from . import stock_picking
from . import stock_picking_container
from . import res_config_settings
from . import material_template
from . import stock_move
from . import stock_move_line
from . import stock_location
from . import stock_picking_consumption_line
from . import transport_product_line
from . import stock_warehouse
from . import transport_leg
from . import stock_package_type
